name: Build with OpenSSL
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: install packages
      run: choco install openssl
    - name: submodules
      run: git submodule update --init --recursive --depth 1
    - name: cmake
      run: cmake -B build -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DUSE_GNUTLS=0 -WARNINGS_AS_ERRORS=1
    - name: nmake
      run: |
        cd build
        set CL=/MP
        nmake
    - name: test
      run: build/tests.exe
    - uses: actions/upload-artifact@master
      with:
          name: BUILD
          path: build

